name: Generate Timetable

on:
  schedule:
    - cron: "*/5 * * * *" # 5分ごと（必要なら変更）
  workflow_dispatch: # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install jpholiday pytz

      - name: Run script
        run: python app.py

      - name: Check output directory
        run: |
          echo "Checking output/ directory contents..."
          ls -al output || echo "output/ directory not found"

      - name: Show generated timetable.txt
        run: |
          echo "Showing content of output/timetable.txt..."
          cat output/timetable.txt || echo "timetable.txt not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
